#!/bin/bash
# QUICK START GUIDE - Habits Monitor Application

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Habitos Monitor - Java 21 LTS - Deployed ✅                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Working Directory
APP_DIR="/home/melsantos/code/habits-app"

# Useful Commands
echo "📦 STARTUP COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Start all containers"
echo "cd $APP_DIR && podman-compose up -d"
echo ""
echo "# Check if containers are running"
echo "podman ps | grep habitos"
echo ""
echo "# Wait for app startup (5-8 seconds)"
echo "sleep 8"
echo ""

echo "🧪 API TEST COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Test Health Endpoint"
echo "curl http://localhost:8080/actuator/health"
echo ""
echo "# Create a Test User"
echo "curl -X POST http://localhost:8080/api/usuarios \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"nome\":\"Test User\",\"email\":\"test@example.com\",\"senha\":\"password123\"}'"
echo ""
echo "# List All Users"
echo "curl http://localhost:8080/api/usuarios"
echo ""
echo "# Get Specific User (replace 1 with actual ID)"
echo "curl http://localhost:8080/api/usuarios/1"
echo ""

echo "📊 DATABASE MANAGEMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Connect to PostgreSQL"
echo "psql -h localhost -U postgres -d habitos_db"
echo ""
echo "# PgAdmin Web Interface"
echo "open http://localhost:5050"
echo "  Email: admin@example.com"
echo "  Password: admin"
echo ""

echo "🔍 TROUBLESHOOTING COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# View Application Logs (live)"
echo "podman logs habitos_app -f"
echo ""
echo "# View Container Status"
echo "podman-compose ps"
echo ""
echo "# Stop All Services"
echo "cd $APP_DIR && podman-compose down"
echo ""
echo "# Rebuild Everything"
echo "cd $APP_DIR && podman-compose down && podman-compose build --no-cache && podman-compose up -d"
echo ""

echo "📋 SERVICE ENDPOINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Spring Boot API       http://localhost:8080/api"
echo "  Health Check          http://localhost:8080/actuator/health"
echo "  PostgreSQL            localhost:5432"
echo "  PgAdmin               http://localhost:5050"
echo ""

echo "ℹ️  CURRENT STATUS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
printf "  Containers Running:   "
podman ps | grep habitos | wc -l
echo "  PostgreSQL Status:     $(podman ps | grep habitos_postgres | awk '{print $NF}' 2>/dev/null || echo 'Not running')"
echo "  PgAdmin Status:        $(podman ps | grep habitos_pgadmin | awk '{print $NF}' 2>/dev/null || echo 'Not running')"
echo "  API Status:            $(podman ps | grep habitos_app | awk '{print $NF}' 2>/dev/null || echo 'Not running')"
echo ""

echo "🎯 QUICK TEST (copy & paste)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Start and verify the application is running"
echo "cd $APP_DIR && podman-compose up -d && sleep 8 && \\"
echo "curl -X POST http://localhost:8080/api/usuarios \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"nome\":\"Quick Test\",\"email\":\"test@test.com\",\"senha\":\"123456\"}'"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "For more information, see: DEPLOYMENT_COMPLETE.md"
echo "═══════════════════════════════════════════════════════════"
echo ""
